import { createFileRoute } from "@tanstack/react-router";
import { LegalLayout } from "@/components/legal-layout";

export const Route = createFileRoute("/legal/risk")({
  head: () => ({
    meta: [
      { title: "Risk Disclosure | TheFortFX" },
      { name: "description", content: "Forex trading carries a high level of risk. Read TheFortFX's full risk disclosure before using our signals, forecasts or analytics." },
      { property: "og:title", content: "Risk Disclosure | TheFortFX" },
      { property: "og:description", content: "Forex trading carries a high level of risk. Read our full risk disclosure." },
      { property: "og:url", content: "/legal/risk" },
    ],
    links: [{ rel: "canonical", href: "/legal/risk" }],
  }),
  component: () => (
    <LegalLayout eyebrow="Risk" title="Risk Disclosure" description="Trading forex and CFDs involves substantial risk. Please read this disclosure in full." updated="June 1, 2026">
      <h2>1. High-risk product</h2>
      <p>Foreign exchange ("forex"), CFDs and leveraged instruments are complex, high-risk products. A large majority of retail trader accounts lose money. You should not trade with funds you cannot afford to lose.</p>
      <h2>2. Leverage</h2>
      <p>Leverage amplifies both gains and losses. A small adverse market move can result in losses exceeding your initial deposit on some products.</p>
      <h2>3. Past performance</h2>
      <p>Past performance — whether shown by us, by a third party, or generated by our models — is not a reliable indicator of future results. Backtests are hypothetical and do not reflect real execution conditions.</p>
      <h2>4. No advice</h2>
      <p>TheFortFX provides research and analytics. We do not provide personalized investment advice, and no signal, forecast or commentary constitutes a recommendation to buy, sell or hold any instrument.</p>
      <h2>5. Execution and slippage</h2>
      <p>We do not execute trades. Any orders you place are executed by your broker under their terms. Spreads, slippage and requotes may materially affect outcomes.</p>
      <h2>6. Market and liquidity risk</h2>
      <p>Markets can gap, especially around news events and at session opens. Liquidity can disappear during high-impact events, widening spreads and increasing slippage.</p>
      <h2>7. Technology risk</h2>
      <p>Internet connectivity, exchange feeds, broker platforms and our own systems can fail. Always have a fallback plan.</p>
      <h2>8. Tax</h2>
      <p>Trading profits and losses may have tax consequences in your jurisdiction. Consult a qualified tax professional.</p>
      <h2>9. Jurisdiction</h2>
      <p>You are responsible for ensuring that trading the relevant instruments is legal where you reside, and for complying with any local registration or licensing requirements.</p>
      <h2>10. Acknowledgement</h2>
      <p>By using TheFortFX, you acknowledge that you have read, understood and accepted this Risk Disclosure.</p>
    </LegalLayout>
  ),
});
