from __future__ import annotations
from typing import Optional, List
from pydantic import BaseModel, Field

class AITradeAnalysisRequest(BaseModel):
    """API contract for requesting AI analysis of a trade setup."""
    pair: str
    direction: str  # BUY or SELL
    entry: float
    stop_loss: float
    take_profit: float
    timeframe: str = "daily"
    notes: Optional[str] = None

class AITradeAnalysisResponse(BaseModel):
    """API contract returning structural trading insights generated by AI."""
    trade_score: int = Field(description="Score from 0 to 100 on the viability of the trade setup")
    confidence_rating: str = Field(description="High, Medium, or Low confidence rating")
    risk_rating: str = Field(description="High, Medium, or Low risk rating")
    sentiment_assessment: str = Field(description="Quick summary of current market sentiment")
    improvements: List[str] = Field(default_factory=list, description="Suggestions for improving the trade setup")
    warnings: List[str] = Field(default_factory=list, description="Potential red flags or warnings")
    summary: str = Field(description="Detailed textual explanation of the analysis")
