/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalsIndexRouteImport } from './routes/signals.index'
import { Route as ForecastsIndexRouteImport } from './routes/forecasts.index'
import { Route as SignalsPairRouteImport } from './routes/signals.$pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsIndexRoute = ForecastsIndexRouteImport.update({
  id: '/forecasts/',
  path: '/forecasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsPairRoute = SignalsPairRouteImport.update({
  id: '/signals/$pair',
  path: '/signals/$pair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signals/$pair': typeof SignalsPairRoute
  '/forecasts/': typeof ForecastsIndexRoute
  '/signals/': typeof SignalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signals/$pair': typeof SignalsPairRoute
  '/forecasts': typeof ForecastsIndexRoute
  '/signals': typeof SignalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signals/$pair': typeof SignalsPairRoute
  '/forecasts/': typeof ForecastsIndexRoute
  '/signals/': typeof SignalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signals/$pair' | '/forecasts/' | '/signals/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signals/$pair' | '/forecasts' | '/signals'
  id: '__root__' | '/' | '/signals/$pair' | '/forecasts/' | '/signals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignalsPairRoute: typeof SignalsPairRoute
  ForecastsIndexRoute: typeof ForecastsIndexRoute
  SignalsIndexRoute: typeof SignalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/': {
      id: '/signals/'
      path: '/signals'
      fullPath: '/signals/'
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts/': {
      id: '/forecasts/'
      path: '/forecasts'
      fullPath: '/forecasts/'
      preLoaderRoute: typeof ForecastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/$pair': {
      id: '/signals/$pair'
      path: '/signals/$pair'
      fullPath: '/signals/$pair'
      preLoaderRoute: typeof SignalsPairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignalsPairRoute: SignalsPairRoute,
  ForecastsIndexRoute: ForecastsIndexRoute,
  SignalsIndexRoute: SignalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
