/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as EconomicCalendarRouteImport } from './routes/economic-calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalsIndexRouteImport } from './routes/signals.index'
import { Route as ForecastsIndexRouteImport } from './routes/forecasts.index'
import { Route as CalculatorsIndexRouteImport } from './routes/calculators.index'
import { Route as SignalsPairRouteImport } from './routes/signals.$pair'
import { Route as ForecastsPairRouteImport } from './routes/forecasts.$pair'
import { Route as CalculatorsPositionSizeRouteImport } from './routes/calculators.position-size'
import { Route as CalculatorsPipCalculatorRouteImport } from './routes/calculators.pip-calculator'

const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicCalendarRoute = EconomicCalendarRouteImport.update({
  id: '/economic-calendar',
  path: '/economic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsIndexRoute = ForecastsIndexRouteImport.update({
  id: '/forecasts/',
  path: '/forecasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsIndexRoute = CalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsPairRoute = SignalsPairRouteImport.update({
  id: '/signals/$pair',
  path: '/signals/$pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsPairRoute = ForecastsPairRouteImport.update({
  id: '/forecasts/$pair',
  path: '/forecasts/$pair',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsPositionSizeRoute = CalculatorsPositionSizeRouteImport.update({
  id: '/calculators/position-size',
  path: '/calculators/position-size',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsPipCalculatorRoute =
  CalculatorsPipCalculatorRouteImport.update({
    id: '/calculators/pip-calculator',
    path: '/calculators/pip-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/journal': typeof JournalRoute
  '/opportunities': typeof OpportunitiesRoute
  '/calculators/pip-calculator': typeof CalculatorsPipCalculatorRoute
  '/calculators/position-size': typeof CalculatorsPositionSizeRoute
  '/forecasts/$pair': typeof ForecastsPairRoute
  '/signals/$pair': typeof SignalsPairRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/forecasts/': typeof ForecastsIndexRoute
  '/signals/': typeof SignalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/journal': typeof JournalRoute
  '/opportunities': typeof OpportunitiesRoute
  '/calculators/pip-calculator': typeof CalculatorsPipCalculatorRoute
  '/calculators/position-size': typeof CalculatorsPositionSizeRoute
  '/forecasts/$pair': typeof ForecastsPairRoute
  '/signals/$pair': typeof SignalsPairRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/forecasts': typeof ForecastsIndexRoute
  '/signals': typeof SignalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/journal': typeof JournalRoute
  '/opportunities': typeof OpportunitiesRoute
  '/calculators/pip-calculator': typeof CalculatorsPipCalculatorRoute
  '/calculators/position-size': typeof CalculatorsPositionSizeRoute
  '/forecasts/$pair': typeof ForecastsPairRoute
  '/signals/$pair': typeof SignalsPairRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/forecasts/': typeof ForecastsIndexRoute
  '/signals/': typeof SignalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/economic-calendar'
    | '/journal'
    | '/opportunities'
    | '/calculators/pip-calculator'
    | '/calculators/position-size'
    | '/forecasts/$pair'
    | '/signals/$pair'
    | '/calculators/'
    | '/forecasts/'
    | '/signals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/economic-calendar'
    | '/journal'
    | '/opportunities'
    | '/calculators/pip-calculator'
    | '/calculators/position-size'
    | '/forecasts/$pair'
    | '/signals/$pair'
    | '/calculators'
    | '/forecasts'
    | '/signals'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/economic-calendar'
    | '/journal'
    | '/opportunities'
    | '/calculators/pip-calculator'
    | '/calculators/position-size'
    | '/forecasts/$pair'
    | '/signals/$pair'
    | '/calculators/'
    | '/forecasts/'
    | '/signals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EconomicCalendarRoute: typeof EconomicCalendarRoute
  JournalRoute: typeof JournalRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  CalculatorsPipCalculatorRoute: typeof CalculatorsPipCalculatorRoute
  CalculatorsPositionSizeRoute: typeof CalculatorsPositionSizeRoute
  ForecastsPairRoute: typeof ForecastsPairRoute
  SignalsPairRoute: typeof SignalsPairRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
  ForecastsIndexRoute: typeof ForecastsIndexRoute
  SignalsIndexRoute: typeof SignalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economic-calendar': {
      id: '/economic-calendar'
      path: '/economic-calendar'
      fullPath: '/economic-calendar'
      preLoaderRoute: typeof EconomicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/': {
      id: '/signals/'
      path: '/signals'
      fullPath: '/signals/'
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts/': {
      id: '/forecasts/'
      path: '/forecasts'
      fullPath: '/forecasts/'
      preLoaderRoute: typeof ForecastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators/'
      preLoaderRoute: typeof CalculatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/$pair': {
      id: '/signals/$pair'
      path: '/signals/$pair'
      fullPath: '/signals/$pair'
      preLoaderRoute: typeof SignalsPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts/$pair': {
      id: '/forecasts/$pair'
      path: '/forecasts/$pair'
      fullPath: '/forecasts/$pair'
      preLoaderRoute: typeof ForecastsPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/position-size': {
      id: '/calculators/position-size'
      path: '/calculators/position-size'
      fullPath: '/calculators/position-size'
      preLoaderRoute: typeof CalculatorsPositionSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/pip-calculator': {
      id: '/calculators/pip-calculator'
      path: '/calculators/pip-calculator'
      fullPath: '/calculators/pip-calculator'
      preLoaderRoute: typeof CalculatorsPipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EconomicCalendarRoute: EconomicCalendarRoute,
  JournalRoute: JournalRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  CalculatorsPipCalculatorRoute: CalculatorsPipCalculatorRoute,
  CalculatorsPositionSizeRoute: CalculatorsPositionSizeRoute,
  ForecastsPairRoute: ForecastsPairRoute,
  SignalsPairRoute: SignalsPairRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
  ForecastsIndexRoute: ForecastsIndexRoute,
  SignalsIndexRoute: SignalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
